/* 專篇釋義：按作者及篇名定位；取景與題字仍以內建原文為準。 */
(function(root) {
  'use strict';
  const data = root.CLASSICAL_LITERATURE_DATA || [];
  const profiles = {};
  function add(author, title, meaning, anchor, motifs, options = {}, exclude = [], note = '') {
    const item = data.find(x => x.author === author && x.title.startsWith(title));
    if (!item) throw new Error('釋義未能定位原篇：'+author+'|'+title);
    const text = item.lines.join('\n');
    const focus = anchor ? (text.split('\n').find(p => p.includes(anchor)) || '') : text;
    if (anchor && !focus) throw new Error('取景依據不存在：'+title+'|'+anchor);
    const scene = { label: options.label || title+'・原文取景', focus, motifs, options,
      representation: options.representation || 'literal', exclude, note };
    profiles[author+'|'+item.title] = { meaning, scenes:[scene], constraints: exclude.length ? ['省略未出現或與本段修辭衝突的景物'] : [] };
    return profiles[author+'|'+item.title];
  }
  add('《山海經》','精衛填海','失去生命後仍銜木石填海，以不屈的行動表現意志','常銜西山之木石',['sea','bird','stone'],{birdCount:1,birdAction:'carry_stone'},[], '鳥銜木石面向海面；不把它畫成泛舟遊賞。');
  add('古歌謠','越人歌','同舟的欣喜與未被理解的愛慕相交','得與王子同舟',['river','boat','person'],{personCount:2},['sunset'], '山木枝是情意的比興，不另造夕陽秋林。');
  add('古歌謠','擊壤歌','勞作飲食與自足的田園生活',null,['field','person','sun'],{personAction:'farm'},[]);
  add('《列子》','高山流水','知音在理解心志，不在堆砌高山流水','伯牙善鼓琴',['qin','person'],{personCount:2},['mountain','river'], '山水是琴聲寄志的比喻；以伯牙與子期的對坐為主。');
  add('《列子》','愚公移山','以長久行動與代際接續面對艱難', '叩石墾壤', ['mountain','person','stone'],{personAction:'work'},[]);
  add('《呂氏春秋》','刻舟求劍','舟動劍止，諷刺拘泥舊位置而不知變通',null,['river','boat','sword','person'],{swordUnderwater:true},[], '劍在水下，刻痕在舟上，兩者的位置分離。');
  add('孟子','揠苗助長','拔苗使苗枯，違反生長規律的好意造成傷害',null,['field','person'],{withered:true,personAction:'farm'},['flower'], '苗已枯槁，不能畫作欣欣向榮。');
  add('莊子','庖丁解牛','依循事物結構而遊刃有餘，由技入道','臣之所好者',['sword'],{representation:'symbolic'},[], '以刀與留白象徵有間無厚，標示象徵構圖，不杜撰山水。');
  add('莊子','知魚之樂','濠梁對話探問理解他者的可能','濠梁',['bridge','river','fish','person'],{personCount:2},[], '橋上二人，水下游魚；畫面呈現辯論場景，不替哲學爭論下定論。');
  add('莊子','逍遙遊','此節錄談大瓠與無用之樹，從用途束縛轉向自在','今子有大樹',['tree'],{representation:'symbolic'},['bird'], '內建節錄沒有鯤鵬，不挪用其他段落的鯤鵬圖。');
  const cai = add('《詩經》','小雅・采薇','戍役歸途的飢渴悲傷，昔日與今日形成對照','昔我往矣',['snow','path','person'],{label:'今歸・雨雪霏霏',personAction:'walk'},['willow','bird'], '只畫今日歸途；昔日楊柳不與今日雪景混作春遊。');
  cai.scenes.push({label:'昔往・楊柳依依',focus:'昔我往矣，楊柳依依',motifs:['willow','person'],representation:'recollection',options:{personAction:'walk'},exclude:['snow'],note:'回憶出征時的景物，與歸途雨雪分開取景。'});
  add('《詩經》','秦風・蒹葭','隔水追尋而不得，距離與阻隔形成朦朧牽念',null,['river','reeds','person'],{personCount:2,distantPerson:true},['boat','snow'], '白露為霜，不等於大雪；伊人在隔水遠處。');
  add('《詩經》','周南・關雎','河洲鳥鳴引出求偶與思慕',null,['river','bird'],{birdCount:2},[], '成對水鳥與河洲表現起興，不補寒舟。');
  add('《詩經》','周南・桃夭','桃花起興，祝願婚姻與家庭和美',null,['peach'],{},['snow','boat']);
  add('古詩十九首','迢迢牽牛星','隔河相望的離愁，以星辰與織作寄情',null,[],{representation:'calligraphy'},['river','boat'], '銀河與星神不套作地面江河；以原詩題跋保留天上想像。');
  add('漢樂府','十五從軍征','年少從軍老年歸家，只見家園荒蕪與親人凋零','遙望是君家',['house','tree','person'],{withered:true,personCount:1},['sunset'], '荒屋與孤老為主，不美化戰爭為凱旋盛景。');
  add('漢樂府','江南','採蓮與魚戲蓮葉的生命活力',null,['pond','lotus','fish'],{fishCount:4},['mountain','snow']);
  add('王羲之','蘭亭集序','宴集之樂轉為生命有限的感慨，珍視人與人共同的感受','引以為流觴曲水',['river','cup','person'],{personCount:4},['qin','flute'], '取流觴曲水宴集；原文明言無絲竹管絃之盛，不畫樂隊。');
  const tao=add('陶潛','桃花源記','避亂者安居自足，桃源理想與後來不可復得相映','土地平曠',['house','field','bamboo','pond','person'],{personCount:3,personAction:'farm'},['boat'], '漁人已捨船進入村落，村內不置孤舟。');
  tao.scenes.push({label:'入境・桃林夾岸',focus:tao ? data.find(x=>x.title==='桃花源記').lines[0] : '',motifs:['river','peach','boat'],representation:'literal',options:{},exclude:[],note:'進入桃源之前的溪行，與村內田園分景。'});
  add('陶潛','飲酒（其五）','心遠而地偏，在人境中體會悠然自得',null,['mountain','chrysanthemum','fence','person','bird','sunset'],{personAction:'pick_flower',birdCount:2},['horse']);
  add('陶潛','歸園田居（其一）','擺脫塵網，回到田園與本性',null,['house','field','tree'],{},['boat']);
  add('陶潛','歸園田居（其三）','勞作辛苦仍不違心願',null,['field','person','moon'],{personAction:'farm'},['boat']);
  add('王維','山居秋暝','新雨秋山中有明月、松泉與人事，是可留之境',null,['mountain','pine','river','moon','lotus','boat','person'],{personCount:2},['snow','sunset']);
  add('王維','竹里館','獨坐彈琴長嘯，明月相照的自得',null,['bamboo','qin','person','moon'],{personAction:'qin'},['boat','sunset']);
  add('王維','鹿柴','空山聲響與返照青苔，以不可見的人聲襯幽靜',null,['mountain','tree','sun'],{lightOnMoss:true},['person','bird','boat'], '不見人不是無聲；返景為夕照的光，不另補月亮。');
  add('王維','相思','紅豆寄相思，願君多採擷',null,[],{representation:'calligraphy'},['mountain','boat'], '目前筆墨圖元未能準確呈現紅豆，以原文題跋保留核心。');
  add('王維','鳥鳴澗','夜靜春山中月出驚鳥，以動襯靜',null,['mountain','moon','bird','flower'],{birdCount:2},['sunset','boat']);
  add('王維','渭城曲','勸酒送別，陽關之外故人難逢',null,['house','willow','cup','person'],{personCount:2},['boat','snow']);
  add('白居易','問劉十九','雪將至時的溫暖邀飲，友情勝於寒意',null,['house','lamp','cup'],{warm:true},['snow','boat','moon'], '天欲雪仍是將然；主體是火爐、新酒與邀友。');
  add('白居易','琵琶行','歌者身世與詩人遭際共鳴，同是天涯淪落人','千呼萬喚始出來',['boat','pipa','person'],{personAction:'pipa',personCount:2},['snow'], '取歌者出場，保留身世共鳴，不將音樂比喻畫成軍隊。');
  add('白居易','暮江吟','殘陽江色至露月夜色的細膩欣賞','一道殘陽',['river','sunset'],{},['moon'], '選夕照一景；夜晚的新月與露珠可在閱讀原文時另觀。');
  add('白居易','賣炭翁','寒苦勞作與權力掠奪的對照','滿面塵灰',['person','tree'],{personAction:'work',withered:true},['boat'], '以勞作者為中心，保留憐憫與批判，不能畫成閒適雪遊。');
  add('岑參','磧中作','平沙夜行而不知何處投宿，旅途荒涼與離家之感',null,['desert','horse','person'],{personAction:'walk'},['smoke','sunset','moon'], '月兩回圓是離家時間；今夜不憑此添滿月，絕人煙不畫孤煙。');
  add('岑參','白雪歌','邊塞奇寒與雪中送別，想像的梨花是雪喻','忽如一夜',['snow','tree'],{withered:true},['peach','plum','sunset'], '梨花作雪的比喻，不畫實際春花。');
  add('李白','月下獨酌','月與影陪伴獨飲，以想像排遣孤獨',null,['moon','cup','person','flower'],{personCount:1,personShadow:true},['boat'], '對影成三人不是三位真實飲者。');
  add('李白','早發白帝城','輕舟疾行穿越萬重山，重獲自由的明快',null,['mountain','river','boat','cloud'],{fastBoat:true},['pavilion','moon'], '白帝城是出發地，不讓樓閣搶走輕舟與江流的主體。');
  add('李白','望廬山瀑布','日照香爐，遙觀瀑布的雄奇',null,['mountain','waterfall','sun'],{},['boat','bird','snow'], '銀河是誇喻，紫煙是水氣，不另造天河或積雪。');
  add('李白','黃鶴樓送孟浩然','目送故人孤帆直至消失，春日江流承載惜別',null,['river','boat'],{distantBoat:true},['pavilion','bird','sunset'], '黃鶴樓是送別起點，孤帆遠影才是視線焦點。');
  add('李白','獨坐敬亭山','鳥盡雲去後，人與敬亭山相對相知',null,['mountain','person'],{personCount:1},['bird','cloud','boat','sunset']);
  add('李白','靜夜思','月光觸發故鄉之思',null,['house','moon','person'],{personCount:1,personAction:'look_moon'},['snow','boat','sunset'], '疑是地上霜是月光錯覺，不畫霜雪山水。');
  const rain=add('李商隱','夜雨寄北','眼前歸期未定與將來共話夜雨的想像相映',null,['house','rain','pond'],{label:'眼前・巴山夜雨'},['lamp','person'], '共剪西窗燭是未來願景，與此刻分景。');
  rain.scenes.push({label:'想像・共剪西窗燭',focus:'何當共剪西窗燭，卻話巴山夜雨時',motifs:['house','lamp','person'],representation:'imagined',options:{personCount:2},exclude:['rain'],note:'未來團聚的想像，不把它當作現在已發生。'});
  add('李商隱','錦瑟','追憶華年而惘然，以多重用典保留含蓄與歧義','錦瑟無端',['qin'],{representation:'symbolic'},['bird','butterfly','sea','mountain'], '以錦瑟為可見主體；莊生、望帝與珠玉均為用典，不拼貼為同一現場。');
  add('杜甫','春望','國破與春生相對，感時傷別而牽念家人',null,['house','flower','person','bird'],{withered:true,personCount:1},['boat','sunset'], '花濺淚與鳥驚心寫人的悲感，不画花朵真的流淚。');
  add('杜甫','旅夜書懷','孤舟旅夜的身世飄零，以沙鷗自況',null,['river','boat','moon'],{},['bird'], '飄飄何所似是自況，不把比喻中的沙鷗當成必然現場。');
  add('杜甫','望嶽','由仰望泰山到凌頂的抱負',null,['mountain','cloud','bird'],{},['boat','pavilion'], '會當凌絕頂是志願，主體仍是所望之嶽。');
  add('杜甫','登高','急風秋江與落木襯出久客、多病、潦倒之悲',null,['river','bare_tree','bird','person'],{personCount:1,birdCount:2},['snow','sunset','boat','cup'], '霜鬢是白髮；新停濁酒杯不可畫成豪飲，登高不是壯志登頂。');
  add('杜甫','絕句','窗前明麗春景與遠山泊船相映',null,['willow','bird','mountain','snow','house','boat'],{birdCount:2,egretLine:true},['moon','sunset'], '兩隻黃鸝在翠柳，白鷺排成一行；雪只落在遠處西嶺。');
  add('杜甫','茅屋為秋風','由自身屋破受寒轉為願天下寒士俱歡顏','八月秋高',['house','rain','person'],{withered:true,personCount:1},['boat','sunset'], '不能將大庇寒士的願望畫成已實現的宮殿盛景。');
  add('孟浩然','春曉','春眠後聞鳥念落花，惜春而不渲染悲壯',null,['bird','flower','house'],{},['rain','sunset','boat'], '夜來風雨是回憶，曉景不持續下夜雨。');
  add('孟浩然','宿建德江','暮泊江渚，日暮新愁與江月近人',null,['river','boat','moon'],{},['sunset'], '取日暮後江月一景，不同時畫日月爭輝。');
  add('柳宗元','江雪','鳥絕人踪滅的天地中，唯釣翁獨對寒江',null,['mountain','snow','river','boat','person'],{personCount:1,personAction:'fish'},['bird','moon','sunset','flower'], '孤舟蓑笠翁是例外的可見人物；月亮與枯樹均非必須物象。');
  add('柳宗元','至小丘西小石潭記','由清潭游魚之樂轉為凄神寒骨的幽邃感','潭中魚',['pond','stone','fish','bamboo'],{fishCount:5},['boat','snake'], '蛇行是溪流形狀的比喻，不畫蛇；以透明留白表現空游無依。');
  add('柳宗元','種樹郭橐駝傳','順應樹木本性，以種樹之理諷繁政擾民','其本欲舒',['tree'],{},['boat'], '不把種樹之道畫成強行束縛或剪裁的奇木。');
  add('韋應物','滁州西澗','幽草黃鸝與急雨春潮，野渡舟橫的幽寂',null,['river','flower','bird','boat','rain'],{emptyBoat:true},['person','moon','sunset'], '野渡無人，舟中不能補釣翁。');
  add('張志和','漁歌子','斜風細雨中的漁者自得',null,['mountain','bird','peach','river','person'],{personAction:'fish',birdCount:1},['snow','moon'], '詞中沒有明言舟船，釣者立岸；不強加雪江孤舟。');
  add('張繼','楓橋夜泊','月落夜泊，鐘聲引出客旅愁眠',null,['river','boat','tree','bird','house'],{},['moon','snow','sunset'], '月已落；寒山寺中的寒不等於雪山。');
  add('温庭筠','菩薩蠻（小山','閨中遲起梳妝，華美外表反襯孤獨',null,['person'],{personCount:1},['mountain','cloud','snow','bird'], '小山、鬢雲、香腮雪與金鷓鴣不可按字面畫成自然山水禽鳥。');
  add('劉禹錫','陋室銘','居室簡陋而德馨，志趣高潔不受俗務拘束','可以調素琴',['house','qin','book'],{},['mountain','river','flute'], '山水、諸葛廬與子雲亭是論證或用典，不把它們併入陋室。');
  add('駱賓王','詠鵝','曲項白鵝紅掌撥水，聲色與動態相映',null,['pond','goose'],{gooseCount:1},['boat','mountain','sunset']);
  add('韓愈','師說','從師在於得道，不受年齡地位束縛','是故弟子不必',[],{representation:'calligraphy'},[], '論述教育原則，採原文主旨題跋，不臆造授課場景。');
  add('王安石','梅花','牆角寒梅以暗香見其品格',null,['wall','plum'],{plumColor:'ink'},['snow','boat','sunset'], '遙知不是雪，不能因雪字補雪景。');
  add('朱熹','觀書有感','以方塘活水比喻求知與精神更新',null,['pond','river','cloud'],{representation:'symbolic'},['boat','mountain'], '水景是有原文依據的比喻構圖，標示象徵而非作者實際泛舟。');
  add('李清照','一剪梅','花水流逝與兩處相思，情感無法排遣','獨上蘭舟',['pond','lotus','boat','person'],{personCount:1},['plum','sunset'], '一剪梅是詞牌，不能據此畫梅花；月樓與蘭舟不合併為同一時刻。');
  add('李清照','聲聲慢','失落與孤獨層層累積，至黃昏雨聲更添悲苦','滿地黃花',['house','chrysanthemum','tree','rain'],{withered:true},['plum','boat','snow'], '黃花是菊，憔悴損不渲染為華麗盛春。');
  add('李清照','醉花陰','重陽黃花寄離愁，人比花瘦',null,['chrysanthemum','fence','cup'],{},['snow','boat']);
  const dream=add('辛棄疾','破陣子','夢中恢復山河的豪情，結尾白髮回到失意現實','醉裏挑燈',['lamp','sword','person'],{label:'現實・挑燈看劍',personCount:1},['horse','desert'], '以現實燈劍承載夢與白髮的落差，不把夢中戰事當成已完成。');
  dream.scenes.push({label:'夢境・沙場點兵',focus:'馬作的盧飛快，弓如霹靂弦驚',motifs:['horse','person'],representation:'dream',options:{personCount:1},exclude:['moon'],note:'明確標示夢境；不將軍功願望當作史實。'});
  add('辛棄疾','青玉案','燈火繁華中尋到獨立於喧鬧之外的人','東風夜放',['lamp','person'],{personCount:2,lanterns:true},['tree','snow','boat'], '花千樹是元夕燈火，不畫成真實花樹。');
  add('周邦彥','蘇幕遮','夏日風荷引出故鄉與夢歸的牽念','水面清圓',['pond','lotus','sun'],{},['boat','snow'], '夢入芙蓉浦與眼前風荷分开，不添現場夢舟。');
  add('周敦頤','愛蓮說','蓮喻君子，清潔自守而不媚俗','予獨愛蓮',['pond','lotus'],{representation:'symbolic'},['chrysanthemum','plum','peach','boat'], '菊與牡丹是比較對象，主體只留蓮，不拼作百花圖。');
  const yue=add('范仲淹','岳陽樓記','以陰晴悲喜作對照，最後提出超越己悲己喜的憂樂責任','至若春和景明',['pond','bird','fish','flower'],{label:'春和景明・洞庭晴景',birdCount:2},['moon','sunset','waves'], '取白晝晴景，原段後半月夜另屬一時；主旨題跋保留先憂後樂。');
  yue.scenes[0].focus='至若春和景明，波瀾不驚，上下天光，一碧萬頃，沙鷗翔集，錦鱗游泳，岸芷汀蘭，郁郁青青';
  yue.scenes[0].motifs=[{id:'pond',evidence:'在洞庭一湖'},'bird','fish'];
  yue.scenes.push({label:'霪雨霏霏・洞庭陰景',focus:'若夫霪雨霏霏，連月不開，陰風怒號，濁浪排空，日星隱曜，山岳潛形',motifs:['rain','waves'],representation:'literal',options:{},exclude:['sun','moon','bird','mountain'],note:'日星隱曜、山岳潛形，日月山形不補亮；阴景並非全篇最終主張。'});
  yue.scenes.push({label:'先憂後樂・主旨題跋',focus:'先天下之憂而憂，後天下之樂而樂',motifs:[],representation:'calligraphy',options:{},exclude:[],note:'將全篇結語置於中心，用題跋留白表現公共責任。'});
  add('陸游','卜算子・詠梅','風雨零落仍不改其香，寄托品格與處境',null,['bridge','plum','rain'],{plumColor:'ink',withered:true},['boat','snow','sunset'], '無主梅與斷橋，不能畫作傲雪豔梅盛景。');
  add('楊萬里','小池','微小初生的荷尖與蜻蜓，生動細緻',null,['pond','lotus','dragonfly'],{lotusBud:true},['boat','mountain','sunset'], '蜻蜓立在初露荷尖，不能畫成滿池盛開蓮花。');
  add('楊萬里','曉出淨慈寺','盛夏接天蓮葉與映日荷花的宏闊',null,['pond','lotus','sun'],{lotusCount:7},['boat','snow']);
  add('趙師秀','約客','梅雨夜候客不至，閒敲棋子落燈花',null,['house','rain','lamp','chess'],{},['plum','boat','snow'], '黃梅時節是梅雨季，不據梅字畫冬梅。');
  add('蘇軾','卜算子（缺月','孤鴻不肯棲寒枝，映照孤高心境',null,['bird','bare_tree','moon'],{birdCount:1,crescent:true,representation:'symbolic'},['boat','snow']);
  add('蘇軾','水調歌頭','對月思親，由離別感嘆轉為相隔而共享明月',null,['moon','person','cup'],{personCount:1},['boat','river','snow'], '雪字、瓊樓玉宇與乘風歸去不可合成江雪仙山現場。');
  add('蘇軾','定風波','遇雨而從容，從實際風雨走向超然心境','莫聽穿林',['path','person','rain'],{personCount:1,personAction:'walk'},['bamboo','horse','boat','snow'], '竹杖是手杖，不是竹林；輕勝馬不必畫馬，雨晴有先後。');
  add('蘇軾','念奴嬌 赤壁懷古','眼前江山引出英雄追想，再回到人生如夢的自省','亂石穿空',['mountain','river','waves','stone'],{},['snow','boat','person','moon'], '取江岸驚濤一景；千堆雪是浪，公瑾是遙想，不偽造蘇子乘舟。');
  add('蘇軾','前赤壁賦','泛舟之樂、生命之悲與共享風月的曠達相互轉化','清風徐來',['river','boat','moon','person','cup'],{personCount:2,calmWater:true},['waves','bird','snow'], '清風徐來、水波不興，不能套赤壁懷古的巨浪或歷史戰艦。');
  add('蘇軾','記承天寺夜遊','月夜同行的閒適中含有貶居者的寂寥','庭下如積水',['house','bamboo','pine','moon'],{castShadows:true},['pond','river','boat','fish'], '庭下積水空明是月光，藻荇是竹柏影，不是真水與水草。');
  add('蘇軾','惠崇春江晚景','從桃花鴨水感知春暖，畫外想像使詩意延伸',null,['river','peach','bird','bamboo'],{birdCount:2,waterBirds:true},['fish','snow'], '河豚欲上是推想，畫面以桃花、竹與水鳥為主。');
  add('蘇軾','題西林壁','觀看位置改變山形，提醒認識受視角限制',null,['mountain'],{multipleViews:true},['bird','boat','sunset'], '不同視角的山形為主，不以豪情登頂取代認識反思。');
  add('蘇軾','飲湖上初晴後雨','晴雨各有其美，西子是比喻而非畫中必然人物',null,['pond','mountain','rain'],{},['person','boat','sunset'], '只取雨景；西子不按字面畫成湖中仕女。');
  add('王冕','墨梅','淡墨梅花寄清氣與不求艷色的品格',null,['plum','pond'],{plumColor:'ink'},['snow','sunset','bird'], '花瓣用淡墨，不用朱砂渲染好顏色。');
  add('王冕','素梅','梅花借月與清影見其素潔',null,['plum'],{plumColor:'ink'},['snow','sunset']);
  add('馬致遠','天淨沙・秋思','羈旅者的斷腸與家園景象相對',null,['bare_tree','bird','bridge','river','house','path','horse','person','sunset'],{withered:true,birdCount:1,personCount:1},['boat','snow'], '瘦馬、古道、昏鴉與旅人構成離愁；小橋人家不是歡樂春遊。');
  add('于謙','石灰吟','以石灰鍛煉與清白寄托不屈品格',null,['stone'],{representation:'symbolic'},['mountain','sunset','boat'], '山只是原料來源；以石與留白象徵清白，保留烈火與粉身的文本意味。');
  add('唐寅','畫雞','雄雞報曉的威儀與勤勉',null,['bird'],{birdCount:1,rooster:true},['mountain','boat']);
  add('魏學洢','核舟記','微小核雕中的精巧技藝與人物情態','船頭坐三人',['boat','person','book'],{personCount:5,miniature:true},['river','moon','mountain'], '核舟是桌上微型雕刻；山高月小、清風水波是雕刻文字，不是真江面。');
  add('歸有光','項脊軒志','書齋生活、家人記憶與喪親之悲交織','三五之夜',['house','tree','moon'],{castShadows:true},['boat','river'], '選書齋月影，親人不同時段的回憶不拼成現場團聚。');
  add('林覺民','與妻書','摯愛妻子與願天下人幸福的抉擇相交','意映卿卿',[],{representation:'calligraphy'},['boat','mountain'], '採書信題跋，讓親情與公共理想的原文承載畫意。');
  add('錢大昕','弈喻','旁觀者自以為明，親身下棋才知其難',null,['chess'],{representation:'symbolic'},['boat','mountain']);
  add('鄭燮','竹石','扎根破岩，任風而堅韌',null,['bamboo','stone'],{},['boat','bird','snow']);
  add('龔自珍','己亥雜詩（其一百二十五）','哀嘆社會噤聲，呼籲解放人才與生氣',null,[],{representation:'calligraphy'},['horse','cloud','sunset'], '萬馬齊喑比喻沉寂，天公風雷與人才之願不能畫成實際馬群天神。');
  add('龔自珍','己亥雜詩（其五）','離愁中仍願以自身滋養新生',null,['flower'],{fallenFlowers:true,representation:'symbolic'},['willow','boat'], '落紅化泥護花承載奉獻主旨，不套江南柳岸。');
  add('龔自珍','病梅館記','批判扭曲生機的審美與束縛，療梅寄托解放人才的願望','既泣之三日',['plum','broken_pot'],{naturalGrowth:true,plumColor:'ink'},['snow','boat','sunset','mountain'], '取解縛、毀盆、入地療梅；枝幹向上舒展，不把病態曲枝當美的標準。');
  root.LITERARY_WORK_PROFILES = profiles;
  if (typeof module !== 'undefined' && module.exports) module.exports = profiles;
})(typeof window !== 'undefined' ? window : globalThis);
